### ISSUE TITLE
Could not find image: no such id: quay.io/travisci/travis-xxx:latest

### ISSUE THREAD

**Issue by MarcJose** [travis-ci/worker#302] opened 2017-04-13 07:42 UTC
When trying to install travis-ci/worker via `./bin/travis-worker-install` I get:
> latest: Pulling from quay.io/travisci/travis-ruby
> 511136ea3c5a: Already exists
> bc1f0427b833: Already exists
> 0cf29d6c76b4: Already exists
> b560c37f1efa: Already exists
> 69c02692b0c1: Already exists
> 18bb34c4d5de: Already exists
> 0cb3406d162a: Already exists
> a054df88b84d: Already exists
> 1d2dceaa3088: Already exists
> 5c12541b06a6: Already exists
> 6a927ef6bd71: Already exists
> bafbb3c33652: Already exists
> ffb7430cc29e: Already exists
> 77b54ec89152: Already exists
> 276af20c9081: Already exists
> 56ef0acdeadb: Already exists
> 6cf578cf4a1f: Already exists
> 1bd392deef90: Already exists
> c65ae5c5d52b: Already exists
> 5adaf370d628: Already exists
> 3cbd4e5fef2d: Already exists
> 2b412eda4314: Already exists
> ee4f8c49a7d9: Already exists
> Digest: sha256:c2a29ddc7f814649c048c00acaaed76f607abec267fd531680becbc6b77c1b7c
> Status: Image is up to date for quay.io/travisci/travis-ruby:latest
> Error response from daemon: could not find image: no such id: quay.io/travisci/travis-clojure:latest

Checking the link used by the script it returns a 403 as well so something looks broken there?
Same happens for other languages (travis-java,... not all though).

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment] 2017-04-13 08:23
Hm, maybe clojure and java were merged. There is a `quay.io/travisci/travis-jvm:latest`.

**Comment by MarcJose** [comment] 2017-04-13 08:39
Yes when I use:
```
__pull_docker_images() {
  : ${DOCKER_CMD:=docker}
  : ${DOCKER_IMAGE_LANGUAGES:=jvm ruby}
  : ${DOCKER_IMAGE_LANGUAGE_MAPPINGS:=jvm:java
```
it seems to work again for java.

**Comment by meatballhat** [comment] 2017-05-11 22:16
@MarcJose :wave:  Hello!  The `jvm` image has been used for `clojure` since at least 2014, iiuc, and I don't believe there was a specific `clojure` image before then.  Given the current state of `./bin/travis-worker-install`, I can't explain why this error message is happening:

```
Error response from daemon: could not find image: no such id: quay.io/travisci/travis-clojure:latest
```

Is there additional output available to help us figure this out?

**Comment by MarcJose** [comment] 2017-05-12 05:11
Those images do not exist, the labels are different so I fixed it by using those new labels.
I got the new names from here: https://quay.io/search?q=travis.

**Comment by meatballhat** [comment] 2017-07-13 16:20
I don't understand what we're supposed to be fixing 😅

**Comment by danishkhan** [comment] 2017-08-01 14:52
@meatballhat I noticed when on https://github.com/travis-ci/worker/blob/master/bin/travis-worker-install#L216 when I switched everything to `jvm:whatever-lang` so `jvm:clojure` `jvm:scala` `erlang:elixir` that fixed the problem. Not sure if the issue is with that or what's happening https://github.com/travis-ci/worker/blob/master/bin/travis-worker-install#L225 when it comes to tagging those images

**Comment by meatballhat** [comment] 2017-08-29 15:50
I think this is a case where the divergence is biting us pretty badly.  We haven't been maintaining the precise images on quay.io since the summer of 2015.  We don't use the `travis-worker-install` script for hosted Travis CI.  I'm still unclear on what this issue is all about, so pretty please open a new issue if you feel there's something remaining that needs attention :heart:

**Closed by meatballhat** 2017-08-29 15:50 UTC
Labels: bug

**Comment by MarcJose** [comment] 2017-09-27 14:41
Sorry that I did not reply yet.
The thing about this issue is that in its current state this repository is broken since you cannot execute it due to missing files it tries to pull.
